# Date: 2021-4-9
# Created by:  Kimberly Brock
# Purpose: Class Exercise, Python Push-Ups
#   Each function, when called, should cause an exception to happen
#   Each function should result in one of the four most common exceptions youâ€™ll find.
#   for review: - NameError - TypeError - SyntaxError - AttributeError

# AttributeError
num = 2
num.upper()

# Syntax Error
42.upper()

# TypeError
num1 = 1
num2 = "2"
ans = num1 + num2

# NameError
print ("hello world!")
pirnt ("hello world")

